changelog:
  categories:
    - title: New Features
      labels:
        - enhancement
    - title: Documentation Changes
      labels:
        - documentation
    - title: Bug Fixes
      labels:
        - bug
    - title: Example
      labels:
        - example
    - title: Deprecations
      labels:
        - deprecated
    - title: Other Changes
      labels:
        - "*"
